# helm 3 is being used for vendor cloud
# helm install jenkins jenkins/jenkins --namespace jenkins --values helm/ingress-jenkins-values.yaml

controller::
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "lts-alpine"
  imagePullPolicy: "Always"
  serviceType: ClusterIP
  installPlugins:
  - workflow-durable-task-step:latest
  - blueocean:latest
  - configuration-as-code:latest
  - credentials:latest
  - git:latest
  - git-client:latest
  - github:latest
  - kubernetes:latest
  - pipeline-utility-steps:latest
  - pipeline-model-definition:latest
  - workflow-aggregator:latest
  - ssh-slaves:latest
  - ssh-agent:latest
  - jdk-tool:latest
  - command-launcher:latest
  - github-oauth:latest
  ingress:
    enabled: true
    paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: 50m
      ingress.kubernetes.io/proxy-request-buffering: "off"
    hostName: 192.168.64.51.nip.io
rbac:
  create: true
