# helm 3 is being used for vendor cloud
# ~/helm3/darwin-amd64/helm install jenkins stable/jenkins --namespace jenkins --values helm/ingress-jenkins-values.yaml
# helm 2 installation command is given below:
# helm install stable/jenkins --namespace jenkins --name jenkins --values helm/ingress-jenkins-values.yaml
master:
  tag: "lts-alpine"
  serviceType: ClusterIP
  installPlugins:
  - durable-task:latest
  - workflow-durable-task-step:latest
  - blueocean:latest
  - configuration-as-code:latest
  - credentials:latest
  - ec2:latest
  - git:latest
  - git-client:latest
  - github:latest
  - kubernetes:latest
  - pipeline-utility-steps:latest
  - pipeline-model-definition:latest
  - slack:latest
  - thinBackup:latest
  - workflow-aggregator:latest
  - ssh-slaves:latest
  - ssh-agent:latest
  - jdk-tool:latest
  - command-launcher:latest
  - github-oauth:latest
  - google-compute-engine:latest
  ingress:
    enabled: true
    paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: 50m
      ingress.kubernetes.io/proxy-request-buffering: "off"
    hostName: 192.168.64.51.nip.io
rbac:
  create: true
