# ~/helm3/darwin-amd64/helm install jenkins stable/jenkins --namespace jenkins --values helm/gke-tls-values.yaml
master:
  tag: "lts-alpine"
  cpu: "500m"
  memory: "500Mi"
  serviceType: ClusterIP
  #serviceType: NodePort
  installPlugins:
  - durable-task:latest
  - workflow-durable-task-step:latest
  - blueocean:latest
  - configuration-as-code:latest
  - credentials:latest
  - docker:latest
  - ec2:latest
  - git:latest
  - git-client:latest
  - github:latest
  - kubernetes:latest
  - pipeline-utility-steps:latest
  - pipeline-model-definition:latest
  - slack:latest
  - thinBackup:latest
  - workflow-aggregator:latest
  - ssh-slaves:latest
  - ssh-agent:latest
  - jdk-tool:latest
  - command-launcher:latest
  - github-oauth:latest
  - google-compute-engine:latest
  - pegdown-formatter:latest
  ingress:
    enabled: true
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: 50m
      ingress.kubernetes.io/proxy-request-buffering: "off"
    hostName: example.com
    tls:
      - secretName: example-com-tls
        hosts:
          - example.com
    rules:
      - host: jenkins.example.com
        http:
          paths:
          - path: /
            backend:
              serviceName: jenkins
              servicePort: 8080
rbac:
  create: true