# installing with Helm 2.x
# helm install stable/jenkins --namespace jenkins --name jenkins --values helm/jenkins-values.yaml
master:
  tag: "lts-alpine"
  cpu: "500m"
  memory: "500Mi"
  serviceType: NodePort
  installPlugins:
  - durable-task:latest
  - workflow-durable-task-step:latest
  - blueocean:latest
  - configuration-as-code:latest
  - credentials:latest
  - ec2:latest
  - git:latest
  - git-client:latest
  - github:latest
  - kubernetes:latest
  - pipeline-utility-steps:latest
  - pipeline-model-definition:latest
  - slack:latest
  - thinBackup:latest
  - workflow-aggregator:latest
  - ssh-slaves:latest
  - ssh-agent:latest
  - jdk-tool:latest
  - command-launcher:latest
  - github-oauth:latest
  - google-compute-engine:latest
  - pegdown-formatter:latest
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: 50m
      ingress.kubernetes.io/proxy-request-buffering: "off"
    hostName: 192.168.64.43.nip.io
rbac:
  create: true